In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[ 5, 41],
       [ 0, 76],
       [57, 88],
       [80, 70],
       [84, 56],
       [13, 27],
       [50, 57],
       [39, 63],
       [54, 87],
       [ 7, 52]])

In [5]:
scalarModel = MinMaxScaler()


In [6]:
type(scalarModel)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scalarModel.fit(data)

C:\Users\fkonk\Anaconda3\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scalarModel.transform(data)

array([[ 0.05952381,  0.2295082 ],
       [ 0.        ,  0.80327869],
       [ 0.67857143,  1.        ],
       [ 0.95238095,  0.70491803],
       [ 1.        ,  0.47540984],
       [ 0.1547619 ,  0.        ],
       [ 0.5952381 ,  0.49180328],
       [ 0.46428571,  0.59016393],
       [ 0.64285714,  0.98360656],
       [ 0.08333333,  0.40983607]])

In [9]:
scalarModel.fit_transform(data)

C:\Users\fkonk\Anaconda3\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.05952381,  0.2295082 ],
       [ 0.        ,  0.80327869],
       [ 0.67857143,  1.        ],
       [ 0.95238095,  0.70491803],
       [ 1.        ,  0.47540984],
       [ 0.1547619 ,  0.        ],
       [ 0.5952381 ,  0.49180328],
       [ 0.46428571,  0.59016393],
       [ 0.64285714,  0.98360656],
       [ 0.08333333,  0.40983607]])

In [10]:
import pandas as pd

In [12]:
myData = np.random.randint(0,101,(50,4))
myData

array([[79, 85, 75, 55],
       [86, 12, 59, 14],
       [97, 76, 27, 15],
       [34, 93, 18, 86],
       [60, 62, 28, 41],
       [86,  3, 82, 65],
       [16, 59, 36, 54],
       [39, 54, 50, 86],
       [34, 36, 79, 17],
       [86, 34, 44,  8],
       [58, 91, 37, 17],
       [11, 61,  8, 27],
       [48, 90, 13, 17],
       [95, 36, 68, 14],
       [64, 94, 33, 63],
       [15, 98, 67, 90],
       [68, 40, 64, 77],
       [74, 39, 61, 71],
       [ 4, 68, 21, 69],
       [23, 71, 71, 75],
       [98, 14, 59, 60],
       [ 5, 84,  9, 44],
       [35, 43, 40, 69],
       [43, 47, 39, 83],
       [12, 72, 79, 56],
       [43, 68, 62, 80],
       [14, 74, 47,  3],
       [90,  3, 24, 24],
       [99, 30, 29, 67],
       [70, 54, 30, 11],
       [35, 34, 70, 48],
       [71, 53, 22, 84],
       [95, 28, 78, 16],
       [88, 77, 18, 41],
       [74, 62,  7, 42],
       [29, 52, 70, 15],
       [63, 25, 88, 84],
       [72, 76, 26, 35],
       [24, 71, 67, 79],
       [62, 64, 61, 54],


In [18]:
df = pd.DataFrame(data = myData, columns = ['f1', 'f2', 'f3', 'label'])

In [19]:
df

f1  f2  f3  label
0   79  85  75     55
1   86  12  59     14
2   97  76  27     15
3   34  93  18     86
4   60  62  28     41
5   86   3  82     65
6   16  59  36     54
7   39  54  50     86
8   34  36  79     17
9   86  34  44      8
10  58  91  37     17
11  11  61   8     27
12  48  90  13     17
13  95  36  68     14
14  64  94  33     63
15  15  98  67     90
16  68  40  64     77
17  74  39  61     71
18   4  68  21     69
19  23  71  71     75
20  98  14  59     60
21   5  84   9     44
22  35  43  40     69
23  43  47  39     83
24  12  72  79     56
25  43  68  62     80
26  14  74  47      3
27  90   3  24     24
28  99  30  29     67
29  70  54  30     11
30  35  34  70     48
31  71  53  22     84
32  95  28  78     16
33  88  77  18     41
34  74  62   7     42
35  29  52  70     15
36  63  25  88     84
37  72  76  26     35
38  24  71  67     79
39  62  64  61     54
40  77  47  77     83
41  24  19  70     90
42  51  64  44     88
43  27  18  57     71
44  99  86  25     61
45  56  72  90     92
46   7  11  62     16
47  51  82  97     76
48  62  45  22     14
49   0  43  73     13

In [21]:
X = df[['f1','f2', 'f3']]

In [22]:
y = df['label']

In [23]:
y

0     55
1     14
2     15
3     86
4     41
5     65
6     54
7     86
8     17
9      8
10    17
11    27
12    17
13    14
14    63
15    90
16    77
17    71
18    69
19    75
20    60
21    44
22    69
23    83
24    56
25    80
26     3
27    24
28    67
29    11
30    48
31    84
32    16
33    41
34    42
35    15
36    84
37    35
38    79
39    54
40    83
41    90
42    88
43    71
44    61
45    92
46    16
47    76
48    14
49    13
Name: label, dtype: int32

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [26]:
X_train.shape

(35, 3)

In [27]:
X_test.shape

(15, 3)